---
- name: Create User Account
  hosts: all
  become: true
  tasks:
    - name: Create user Brahim and add to wheel group
      ansible.builtin.user:
        name: Brahim
        comment: "Ansible user Brahim"
        password: '$2y$10$aRZ666fL/7M85NyvB9yW3e4HUfxFCcLeLxamydcyFwF8.kDaCJVxa'
        ssh_key_passphrase: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvNu7Ou6YvhNZ+77Jl4Kd5hZOpK1HUjxlEAJ4yl7qz1CSdDBGkgnC705wJYrQvD6pZINHiu092F9twJloMiSHcIgqNuD3EhtTi9uNV9+e1/aImReKlXshy6z0VTp2iKKde5H+Fb4VeNyfU4E8p8ufytJgAptHC7T6r7fN7GdSbHrptNflwM3Fz1ziDISF+QlbfuxifNbPCjUesBInM3z1/aXJ85GLsIMF7nzQpPOBQKLzBaLWR/cw4XJz4WE0TYCRBBhxdrZJK1YyonbMvNAh5TTU02N8SKoqTAGjoMYHYjWXye6VX7zRb+zoSmzgXxq971aJUjVuaX2S0QKmJ6MM7N+IA2qp1tNkqH3u3XYwSYtV7YZLSvlJ/F8RdOtLiUYwlw42ASUSmc8PUPeqNULjupggYs7rlMaA/TudmBeZ4q+wIhbaYWx/bXgGtdUIpmAJrt1dTlxuRZpl/B5SgHerIjyuTxoQYcD57SpTuiokb9KnxjkA6H8dx/1afgD/7uhc= brahim@LAPTOP-IDKQTGPK'
        groups: 
        - wheel
        system: false
        state: present
        home: /home/Brahim
